chore: add standardization and configuration for markdown
silvermine/silvermine-info pull request #18
Opened 2021-09-10 20:29 UTC by pbredenberg

2021-09-23 15:25 UTC, onebytegone requested changes

2021-09-23 15:25 UTC, onebytegone commented on coding-standards.md
> +        ```
```suggestion
         ```
```

2021-09-24 12:48 UTC, pbredenberg commented on coding-standards.md
> +        ```
You'd like it if these columns line dup, wouldn't you?

2021-09-24 13:06 UTC, pbredenberg commented on coding-standards.md
> +        ```
Fixed

2021-09-24 15:12 UTC, onebytegone requested changes

2021-09-24 15:12 UTC, onebytegone commented on coding-standards.md
> +          echo -n 'this is a test' > /tmp/test-nonewline.txt && echo 'this is a test' > /tmp/test-newline.txt && wc -l /tmp/test-*newline.txt`
Sorry, just noticed the extra space before `echo`

```suggestion
         echo -n 'this is a test' > /tmp/test-nonewline.txt && echo 'this is a test' > /tmp/test-newline.txt && wc -l /tmp/test-*newline.txt`
```

2021-09-24 15:30 UTC, pbredenberg commented on coding-standards.md
> +          echo -n 'this is a test' > /tmp/test-nonewline.txt && echo 'this is a test' > /tmp/test-newline.txt && wc -l /tmp/test-*newline.txt`
That whole fence was all messed up. Should be good now.

2021-09-24 20:17 UTC, onebytegone approved these changes

2021-09-24 20:17 UTC, merged